{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "Profile<uuid='251a7c0fb83e42718a3a51e0ee33ee7a' name='lucia'>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "from aiida import orm, engine, load_profile\n",
    "from aiida.common import NotExistent\n",
    "\n",
    "import aiida_dislocation\n",
    "import importlib\n",
    "# importlib.reload(aiida_dislocation.workflows.usf)\n",
    "from aiida_dislocation.workflows.usf import USFWorkChain\n",
    "\n",
    "from ase.io import read\n",
    "from ase.build import bulk\n",
    "from aiida.engine import run\n",
    "\n",
    "import logging\n",
    "\n",
    "\n",
    "load_profile()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Group 'test/workchains/USF/' already exists.\n"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "group_label = 'test/workchains/USF/'\n",
    "test_USF_group, created = orm.Group.collection.get_or_create(label=group_label)\n",
    "if created:\n",
    "    print(f\"Group '{group_label}' created.\")\n",
    "else:\n",
    "    print(f\"Group '{group_label}' already exists.\")\n",
    "\n",
    "\n",
    "computer = 'lucia'\n",
    "lucia_computer = orm.load_computer(computer)\n",
    "lucia_computer.set_workdir('/gpfs/scratch/acad/elph/yimzhang/aiida_workdir/test_aiida_dislocation')\n",
    "\n",
    "version = '73'\n",
    "code = 'pw'\n",
    "label = f'qe-{version}-{code}'\n",
    "bin_dir = '/gpfs/scratch/acad/elph/yimzhang/apps/q-e-qe-7.3/bin/'\n",
    "try:\n",
    "    orm.load_code(f'{label}@{computer}')\n",
    "except NotExistent as exc:\n",
    "    orm.InstalledCode(\n",
    "        label=label,\n",
    "        description=f'Quantum ESPRESSO {version} version for {code}.x',\n",
    "        computer=lucia_computer,\n",
    "        filepath_executable=f'{bin_dir}/{code}.x',\n",
    "        default_calc_job_plugin=f'quantumespresso.{code}',\n",
    "    ).store()\n",
    "\n",
    "pw_label = f'qe-{version}-pw'\n",
    "pw_code = orm.load_code(f'{pw_label}@{computer}')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# TEST A1 -- Aluminium"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "import yaml\n",
    "\n",
    "ase_atom = read('./structures/cif/Al-225-A1.cif', format='cif')\n",
    "structure = orm.StructureData(ase=ase_atom)\n",
    "\n",
    "pseudo_family = orm.load_group('PseudoDojo/0.5/PBE/SR/standard/upf')\n",
    "\n",
    "pseudos = pseudo_family.get_pseudos(structure=structure)\n",
    "\n",
    "cutoff_wfc, cutoff_rho = pseudo_family.get_recommended_cutoffs(\n",
    "    structure=structure,\n",
    "    unit='Ry'\n",
    ")\n",
    "\n",
    "kpoints = orm.KpointsData()\n",
    "kpoints.set_kpoints_mesh([12, 12, 12])\n",
    "\n",
    "settings = orm.Dict({\n",
    "    # 'cmdline': ['-npool', '2']\n",
    "})\n",
    "\n",
    "usf_overrides_yaml = open('./usf.yaml')\n",
    "usf_overrides = yaml.safe_load(usf_overrides_yaml)\n",
    "\n",
    "inputs = {}\n",
    "\n",
    "inputs['metadata'] = usf_overrides.get('metadata', {})\n",
    "inputs['structure'] = structure\n",
    "inputs['kpoints'] = kpoints\n",
    "inputs['pw'] = usf_overrides.get('pw', {})\n",
    "inputs['pw']['pseudos'] = pseudos\n",
    "inputs['pw']['code'] = pw_code\n",
    "inputs['pw']['parameters']['CONTROL']['disk_io'] = 'nowf'\n",
    "inputs['pw']['parameters']['SYSTEM']['degauss'] = 0.02\n",
    "inputs['pw']['parameters']['ELECTRONS']['conv_thr'] = 1e-5\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## {100} surface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "04/28/2025 10:17:46 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71643|USFWorkChain|validate_slipping_system]: FCC element crystal <space group #225, prototype Cu>. Usually, the gliding plane is 111.\n",
      "04/28/2025 10:17:46 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71643|USFWorkChain|validate_slipping_system]: Now we are working on 100 gliding plane.\n",
      "04/28/2025 10:17:46 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71643|USFWorkChain|validate_slipping_system]: Faulting is possible for 100 gliding plane.The stacking order is AB.Slipping direction: None. \n",
      "04/28/2025 10:17:47 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71643|USFWorkChain|run_scf]: launching PwCalculation<71644> for Al unit cell geometry.\n",
      "04/28/2025 10:21:26 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71643|USFWorkChain|inspect_scf]: SCF calculation<71644> finished\n",
      "04/28/2025 10:21:26 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71643|USFWorkChain|run_USF]: Multiplicity of the faulted geometry: 8\n",
      "04/28/2025 10:21:26 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71643|USFWorkChain|run_USF]: launching PwCalculation<71652> for USF geometry.\n",
      "04/28/2025 10:25:51 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71643|USFWorkChain|inspect_USF]: SCF calculation<71652> for USF geometry finished\n",
      "04/28/2025 10:25:51 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71643|USFWorkChain|results]: Energy difference per surface area: uuid: 3a96df45-7535-43ba-8436-3de47bf5ea7d (unstored) value: 110.44963489182699 J/m^2\n",
      "04/28/2025 10:25:51 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71643|USFWorkChain|results]: Results\n",
      "04/28/2025 10:25:51 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71643|USFWorkChain|on_terminated]: remote folders will not be cleaned\n"
     ]
    }
   ],
   "source": [
    "inputs['skip_uc'] = orm.Bool(False)\n",
    "inputs['n_layers'] =orm.Int(8)\n",
    "inputs['slipping_system'] = orm.List(['A1', '100'])\n",
    "\n",
    "logging.getLogger('aiida.transport.SshTransport').setLevel(logging.ERROR)\n",
    "logging.getLogger('aiida.scheduler.slurm').setLevel(logging.ERROR)\n",
    "\n",
    "test_node = run.get_node(USFWorkChain, **inputs)\n",
    "test_USF_group.add_nodes(test_node.node)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## {110} surface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "04/28/2025 10:40:12 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71677|USFWorkChain|validate_slipping_system]: FCC element crystal <space group #225, prototype Cu>. Usually, the gliding plane is 111.\n",
      "04/28/2025 10:40:12 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71677|USFWorkChain|validate_slipping_system]: Now we are working on 110 gliding plane.\n",
      "04/28/2025 10:40:12 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71677|USFWorkChain|validate_slipping_system]: Faulting is possible for 110 gliding plane.The stacking order is AB. Slipping direction: 1/2[112]. \n",
      "04/28/2025 10:40:12 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [WARNING] You are skipping the unitcell calculation. Hopefully you know what you are doing!\n",
      "04/28/2025 10:40:12 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71677|USFWorkChain|run_USF]: Multiplicity of the faulted geometry: 8\n",
      "04/28/2025 10:40:12 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71677|USFWorkChain|run_USF]: launching PwCalculation<71680> for USF geometry.\n",
      "04/28/2025 10:41:57 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71677|USFWorkChain|inspect_USF]: SCF calculation<71680> for USF geometry finished\n",
      "04/28/2025 10:41:57 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71677|USFWorkChain|results]: Total energy of the faulted geometry: -474.61461166176 eV\n",
      "04/28/2025 10:41:57 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71677|USFWorkChain|results]: Results\n",
      "04/28/2025 10:41:57 AM <158968> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71677|USFWorkChain|on_terminated]: remote folders will not be cleaned\n"
     ]
    }
   ],
   "source": [
    "inputs['skip_uc'] = orm.Bool(True)\n",
    "inputs['n_layers'] =orm.Int(8)\n",
    "inputs['slipping_system'] = orm.List(['A1', '110'])\n",
    "\n",
    "logging.getLogger('aiida.transport.SshTransport') .setLevel(logging.ERROR)\n",
    "logging.getLogger('aiida.scheduler.slurm').setLevel(logging.ERROR)\n",
    "\n",
    "test_node = run.get_node(USFWorkChain, **inputs)\n",
    "test_USF_group.add_nodes(test_node.node)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## {111} surface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "04/28/2025 09:18:10 AM <85805> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71584|USFWorkChain|validate_slipping_system]: We are doing FCC element crystal <space group #225, prototype Cu>. Usually, the gliding plane is 111.\n",
      "04/28/2025 09:18:10 AM <85805> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71584|USFWorkChain|validate_slipping_system]: ABC stacking for {111} gliding plane. Faulting possible. slipping direction is along 1/2[110].\n",
      "04/28/2025 09:18:10 AM <85805> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71584|USFWorkChain|run_scf]: launching PwCalculation<71585> for Al unit cell geometry.\n",
      "04/28/2025 09:21:02 AM <85805> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71584|USFWorkChain|inspect_scf]: SCF calculation<71585> finished\n",
      "04/28/2025 09:21:02 AM <85805> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71584|USFWorkChain|run_USF]: Multiplicity of the faulted geometry: 8\n",
      "04/28/2025 09:21:03 AM <85805> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71584|USFWorkChain|run_USF]: launching PwCalculation<71593> for USF geometry.\n",
      "04/28/2025 09:24:39 AM <85805> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71584|USFWorkChain|inspect_USF]: SCF calculation<71593> for USF geometry finished\n",
      "04/28/2025 09:24:40 AM <85805> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71584|USFWorkChain|results]: Energy difference per surface area: uuid: 0d14f555-a8d1-4fc2-b72a-e8d4ee034bf3 (unstored) value: 5.001486018232243 J/m^2\n",
      "04/28/2025 09:24:40 AM <85805> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71584|USFWorkChain|results]: Results\n",
      "04/28/2025 09:24:40 AM <85805> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71584|USFWorkChain|on_terminated]: remote folders will not be cleaned\n"
     ]
    }
   ],
   "source": [
    "inputs['skip_uc'] = orm.Bool(False)\n",
    "inputs['n_layers'] =orm.Int(9)\n",
    "inputs['slipping_system'] = orm.List(['A1', '111', None])\n",
    "\n",
    "logging.getLogger('aiida.transport.SshTransport').setLevel(logging.ERROR)\n",
    "logging.getLogger('aiida.scheduler.slurm').setLevel(logging.ERROR)\n",
    "\n",
    "test_node = run.get_node(USFWorkChain, **inputs)\n",
    "test_USF_group.add_nodes(test_node.node)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# TEST A2 -- Vanadium"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "import yaml\n",
    "\n",
    "ase_atom = read('./structures/cif/V-227-A2.cif', format='cif')\n",
    "structure = orm.StructureData(ase=ase_atom)\n",
    "\n",
    "pseudo_family = orm.load_group('PseudoDojo/0.5/PBE/SR/standard/upf')\n",
    "\n",
    "pseudos = pseudo_family.get_pseudos(structure=structure)\n",
    "\n",
    "cutoff_wfc, cutoff_rho = pseudo_family.get_recommended_cutoffs(\n",
    "    structure=structure,\n",
    "    unit='Ry'\n",
    ")\n",
    "\n",
    "kpoints = orm.KpointsData()\n",
    "kpoints.set_kpoints_mesh([14, 14, 14])\n",
    "\n",
    "settings = orm.Dict({\n",
    "    # 'cmdline': ['-npool', '2']\n",
    "})\n",
    "\n",
    "usf_overrides_yaml = open('./usf-lucia.yaml')\n",
    "usf_overrides = yaml.safe_load(usf_overrides_yaml)\n",
    "\n",
    "inputs = {}\n",
    "\n",
    "inputs['metadata'] = usf_overrides.get('metadata', {})\n",
    "inputs['structure'] = structure\n",
    "inputs['kpoints'] = kpoints\n",
    "inputs['pw'] = usf_overrides.get('pw', {})\n",
    "inputs['pw']['pseudos'] = pseudos\n",
    "inputs['pw']['code'] = pw_code\n",
    "inputs['pw']['parameters']['CONTROL']['disk_io'] = 'nowf'\n",
    "inputs['pw']['parameters']['SYSTEM']['degauss'] = 0.01\n",
    "inputs['pw']['parameters']['ELECTRONS']['conv_thr'] = 1e-5\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## {100} surface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "04/28/2025 03:17:04 PM <885922> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71900|USFWorkChain|validate_slipping_system]: FCC element crystal <space group #227, prototype V>. I don't know the usual gliding plane. \n",
      "04/28/2025 03:17:04 PM <885922> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71900|USFWorkChain|validate_slipping_system]: Now we are working on 100 gliding plane.\n",
      "04/28/2025 03:17:04 PM <885922> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71900|USFWorkChain|validate_slipping_system]: Faulting is possible for 100 gliding plane.The stacking order is AB. Slipping direction: 1/2[110]. \n",
      "04/28/2025 03:17:04 PM <885922> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71900|USFWorkChain|run_scf]: launching PwCalculation<71901> for V unit cell geometry.\n",
      "04/28/2025 03:17:35 PM <885922> aiida.transport.SshTransport: [ERROR] Error connecting to proxy 'gwceci.cism.ucl.ac.be' through SSH: [SshTransport] Authentication failed., connect_args were: {'username': 'yimzhang', 'port': 22, 'look_for_keys': True, 'key_filename': '/home/ucl/modl/yimzhang/.ssh/id_rsa.ceci', 'timeout': 60, 'allow_agent': True, 'compress': True, 'gss_auth': False, 'gss_kex': False, 'gss_deleg_creds': False, 'gss_host': 'frontal.lucia.cenaero.be'}\n",
      "04/28/2025 03:17:35 PM <885922> aiida.engine.transports: [ERROR] exception occurred while trying to open transport:\n",
      " Authentication failed.\n",
      "04/28/2025 03:17:35 PM <885922> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 86, in do_upload\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "\n",
      "04/28/2025 03:17:35 PM <885922> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 1 of do_upload excepted, retrying after 20 seconds\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 86, in do_upload\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "04/28/2025 03:18:25 PM <885922> aiida.transport.SshTransport: [ERROR] Error connecting to proxy 'gwceci.cism.ucl.ac.be' through SSH: [SshTransport] Authentication failed., connect_args were: {'username': 'yimzhang', 'port': 22, 'look_for_keys': True, 'key_filename': '/home/ucl/modl/yimzhang/.ssh/id_rsa.ceci', 'timeout': 60, 'allow_agent': True, 'compress': True, 'gss_auth': False, 'gss_kex': False, 'gss_deleg_creds': False, 'gss_host': 'frontal.lucia.cenaero.be'}\n",
      "04/28/2025 03:18:25 PM <885922> aiida.engine.transports: [ERROR] exception occurred while trying to open transport:\n",
      " Authentication failed.\n",
      "04/28/2025 03:18:25 PM <885922> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 86, in do_upload\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "\n",
      "04/28/2025 03:18:25 PM <885922> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 2 of do_upload excepted, retrying after 40 seconds\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 86, in do_upload\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "04/28/2025 03:18:50 PM <885922> aiida.engine.runners: [CRITICAL] runner received interrupt, killing process 71900\n",
      "04/28/2025 03:18:51 PM <885922> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [71900|USFWorkChain|on_terminated]: remote folders will not be cleaned\n"
     ]
    },
    {
     "ename": "KilledError",
     "evalue": "Process was killed because the runner received an interrupt",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mKilledError\u001b[39m                               Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[5]\u001b[39m\u001b[32m, line 8\u001b[39m\n\u001b[32m      5\u001b[39m logging.getLogger(\u001b[33m'\u001b[39m\u001b[33maiida.transport.SshTransport\u001b[39m\u001b[33m'\u001b[39m) .setLevel(logging.ERROR)\n\u001b[32m      6\u001b[39m logging.getLogger(\u001b[33m'\u001b[39m\u001b[33maiida.scheduler.slurm\u001b[39m\u001b[33m'\u001b[39m).setLevel(logging.ERROR)\n\u001b[32m----> \u001b[39m\u001b[32m8\u001b[39m test_node = \u001b[43mrun\u001b[49m\u001b[43m.\u001b[49m\u001b[43mget_node\u001b[49m\u001b[43m(\u001b[49m\u001b[43mUSFWorkChain\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43minputs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m      9\u001b[39m test_USF_group.add_nodes(test_node.node)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/launch.py:65\u001b[39m, in \u001b[36mrun_get_node\u001b[39m\u001b[34m(process, inputs, **kwargs)\u001b[39m\n\u001b[32m     62\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m     63\u001b[39m     runner = manager.get_manager().get_runner()\n\u001b[32m---> \u001b[39m\u001b[32m65\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mrunner\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrun_get_node\u001b[49m\u001b[43m(\u001b[49m\u001b[43mprocess\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43minputs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/runners.py:291\u001b[39m, in \u001b[36mRunner.run_get_node\u001b[39m\u001b[34m(self, process, inputs, **kwargs)\u001b[39m\n\u001b[32m    280\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mrun_get_node\u001b[39m(\n\u001b[32m    281\u001b[39m     \u001b[38;5;28mself\u001b[39m, process: TYPE_RUN_PROCESS, inputs: \u001b[38;5;28mdict\u001b[39m[\u001b[38;5;28mstr\u001b[39m, Any] | \u001b[38;5;28;01mNone\u001b[39;00m = \u001b[38;5;28;01mNone\u001b[39;00m, **kwargs: Any\n\u001b[32m    282\u001b[39m ) -> ResultAndNode:\n\u001b[32m    283\u001b[39m \u001b[38;5;250m    \u001b[39m\u001b[33;03m\"\"\"Run the process with the supplied inputs in this runner that will block until the process is completed.\u001b[39;00m\n\u001b[32m    284\u001b[39m \n\u001b[32m    285\u001b[39m \u001b[33;03m    The return value will be the results of the completed process\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    289\u001b[39m \u001b[33;03m    :return: tuple of the outputs of the process and the calculation node\u001b[39;00m\n\u001b[32m    290\u001b[39m \u001b[33;03m    \"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m291\u001b[39m     result, node = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_run\u001b[49m\u001b[43m(\u001b[49m\u001b[43mprocess\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43minputs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    292\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m ResultAndNode(result, node)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/runners.py:261\u001b[39m, in \u001b[36mRunner._run\u001b[39m\u001b[34m(self, process, inputs, **kwargs)\u001b[39m\n\u001b[32m    259\u001b[39m     signal.signal(signal.SIGINT, kill_process)\n\u001b[32m    260\u001b[39m     signal.signal(signal.SIGTERM, kill_process)\n\u001b[32m--> \u001b[39m\u001b[32m261\u001b[39m     \u001b[43mprocess_inited\u001b[49m\u001b[43m.\u001b[49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    262\u001b[39m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[32m    263\u001b[39m     signal.signal(signal.SIGINT, original_handler_int)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/miniforge3/envs/aiida-240/lib/python3.11/site-packages/plumpy/processes.py:86\u001b[39m, in \u001b[36mensure_not_closed.<locals>.func_wrapper\u001b[39m\u001b[34m(self, *args, **kwargs)\u001b[39m\n\u001b[32m     84\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._closed:\n\u001b[32m     85\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m exceptions.ClosedError(\u001b[33m'\u001b[39m\u001b[33mProcess is closed\u001b[39m\u001b[33m'\u001b[39m)\n\u001b[32m---> \u001b[39m\u001b[32m86\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/miniforge3/envs/aiida-240/lib/python3.11/site-packages/plumpy/processes.py:1197\u001b[39m, in \u001b[36mProcess.execute\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m   1194\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m.has_terminated():\n\u001b[32m   1195\u001b[39m     \u001b[38;5;28mself\u001b[39m.loop.run_until_complete(\u001b[38;5;28mself\u001b[39m.step_until_terminated())\n\u001b[32m-> \u001b[39m\u001b[32m1197\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mfuture\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[31mKilledError\u001b[39m: Process was killed because the runner received an interrupt"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "04/28/2025 03:19:05 PM <885922> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 86, in do_upload\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "plumpy.process_states.KillInterruption: Killed by parent<71900>\n",
      "\n",
      "04/28/2025 03:19:21 PM <885922> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 426, in do_kill\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "\n",
      "04/28/2025 03:19:21 PM <885922> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 1 of do_kill excepted, retrying after 20 seconds\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 426, in do_kill\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "04/28/2025 03:20:11 PM <885922> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 426, in do_kill\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "\n",
      "04/28/2025 03:20:11 PM <885922> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 2 of do_kill excepted, retrying after 40 seconds\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 426, in do_kill\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "04/28/2025 03:21:22 PM <885922> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 426, in do_kill\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "\n",
      "04/28/2025 03:21:22 PM <885922> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 3 of do_kill excepted, retrying after 80 seconds\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 426, in do_kill\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "04/28/2025 03:23:12 PM <885922> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 426, in do_kill\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "\n",
      "04/28/2025 03:23:12 PM <885922> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 4 of do_kill excepted, retrying after 160 seconds\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 426, in do_kill\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "04/28/2025 03:26:22 PM <885922> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 426, in do_kill\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "\n",
      "04/28/2025 03:26:22 PM <885922> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 5 of do_kill excepted\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 426, in do_kill\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "04/28/2025 03:26:22 PM <885922> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [WARNING] maximum attempts 5 of calling do_kill, exceeded\n",
      "04/28/2025 03:26:22 PM <885922> aiida.engine.processes.calcjobs.tasks: [WARNING] killing CalcJob<71901> failed\n",
      "04/28/2025 03:26:22 PM <885922> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [REPORT] [71901|PwCalculation|on_except]: Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 426, in do_kill\n",
      "    transport = await cancellable.with_interrupt(request)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 605, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/transports.py\", line 87, in do_open\n",
      "    transport.open()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/transports/plugins/ssh.py\", line 480, in open\n",
      "    proxy_client.connect(proxy['host'], **proxy_connargs)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 450, in connect\n",
      "    self._auth(\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 781, in _auth\n",
      "    raise saved_exception\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/client.py\", line 757, in _auth\n",
      "    self._transport.auth_publickey(username, key)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/transport.py\", line 1635, in auth_publickey\n",
      "    return self.auth_handler.wait_for_response(my_event)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/paramiko/auth_handler.py\", line 259, in wait_for_response\n",
      "    raise e\n",
      "paramiko.ssh_exception.AuthenticationException: Authentication failed.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/plumpy/processes.py\", line 1218, in step\n",
      "    next_state = await self._run_task(self._state.execute)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/plumpy/processes.py\", line 567, in _run_task\n",
      "    result = await coro(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 570, in execute\n",
      "    await self._kill_job(node, transport_queue)\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 623, in _launch_task\n",
      "    result = await self._task\n",
      "             ^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/asyncio/tasks.py\", line 339, in __wakeup\n",
      "    future.result()\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/utils.py\", line 137, in execute_coroutine\n",
      "    result = await coro(future)\n",
      "             ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/ucl/modl/yimzhang/miniforge3/envs/aiida-240/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 436, in task_kill_job\n",
      "    raise TransportTaskException(f'kill_calculation failed {max_attempts} times consecutively') from exception\n",
      "aiida.common.exceptions.TransportTaskException: kill_calculation failed 5 times consecutively\n",
      "\n"
     ]
    }
   ],
   "source": [
    "inputs['skip_uc'] = orm.Bool(False)\n",
    "inputs['n_layers'] =orm.Int(16)\n",
    "inputs['slipping_system'] = orm.List(['A2', '100'])\n",
    "\n",
    "logging.getLogger('aiida.transport.SshTransport') .setLevel(logging.ERROR)\n",
    "logging.getLogger('aiida.scheduler.slurm').setLevel(logging.ERROR)\n",
    "\n",
    "test_node = run.get_node(USFWorkChain, **inputs)\n",
    "test_USF_group.add_nodes(test_node.node)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## {110} surface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "04/28/2025 05:31:49 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137961|USFWorkChain|validate_slipping_system]: FCC element crystal <space group #227, prototype V>. I don't know the usual gliding plane. \n",
      "04/28/2025 05:31:49 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137961|USFWorkChain|validate_slipping_system]: Now we are working on 110 gliding plane.\n",
      "04/28/2025 05:31:49 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137961|USFWorkChain|validate_slipping_system]: Faulting is possible for 110 gliding plane.The stacking order is AB. Slipping direction: 1/2[001]. \n",
      "04/28/2025 05:31:49 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137961|USFWorkChain|run_scf]: launching PwCalculation<1137962> for V unit cell geometry.\n",
      "04/28/2025 05:35:21 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137961|USFWorkChain|inspect_scf]: SCF calculation<1137962> finished\n",
      "04/28/2025 05:35:21 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137961|USFWorkChain|run_USF]: Multiplicity of the faulted geometry: 12\n",
      "04/28/2025 05:35:21 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137961|USFWorkChain|run_USF]: launching PwCalculation<1137970> for USF geometry.\n",
      "04/28/2025 06:51:43 PM <139415> aiida.engine.runners: [CRITICAL] runner received interrupt, killing process 1137961\n",
      "04/28/2025 06:51:43 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137961|USFWorkChain|on_terminated]: remote folders will not be cleaned\n"
     ]
    },
    {
     "ename": "KilledError",
     "evalue": "Process was killed because the runner received an interrupt",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKilledError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[23], line 8\u001b[0m\n\u001b[1;32m      5\u001b[0m logging\u001b[38;5;241m.\u001b[39mgetLogger(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124maiida.transport.SshTransport\u001b[39m\u001b[38;5;124m'\u001b[39m) \u001b[38;5;241m.\u001b[39msetLevel(logging\u001b[38;5;241m.\u001b[39mERROR)\n\u001b[1;32m      6\u001b[0m logging\u001b[38;5;241m.\u001b[39mgetLogger(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124maiida.scheduler.slurm\u001b[39m\u001b[38;5;124m'\u001b[39m)\u001b[38;5;241m.\u001b[39msetLevel(logging\u001b[38;5;241m.\u001b[39mERROR)\n\u001b[0;32m----> 8\u001b[0m test_node \u001b[38;5;241m=\u001b[39m \u001b[43mrun\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_node\u001b[49m\u001b[43m(\u001b[49m\u001b[43mUSFWorkChain\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43minputs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m      9\u001b[0m test_USF_group\u001b[38;5;241m.\u001b[39madd_nodes(test_node\u001b[38;5;241m.\u001b[39mnode)\n",
      "File \u001b[0;32m~/.aiida_venvs/lucia/lib/python3.10/site-packages/aiida/engine/launch.py:65\u001b[0m, in \u001b[0;36mrun_get_node\u001b[0;34m(process, inputs, **kwargs)\u001b[0m\n\u001b[1;32m     62\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     63\u001b[0m     runner \u001b[38;5;241m=\u001b[39m manager\u001b[38;5;241m.\u001b[39mget_manager()\u001b[38;5;241m.\u001b[39mget_runner()\n\u001b[0;32m---> 65\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mrunner\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun_get_node\u001b[49m\u001b[43m(\u001b[49m\u001b[43mprocess\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43minputs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.aiida_venvs/lucia/lib/python3.10/site-packages/aiida/engine/runners.py:291\u001b[0m, in \u001b[0;36mRunner.run_get_node\u001b[0;34m(self, process, inputs, **kwargs)\u001b[0m\n\u001b[1;32m    280\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mrun_get_node\u001b[39m(\n\u001b[1;32m    281\u001b[0m     \u001b[38;5;28mself\u001b[39m, process: TYPE_RUN_PROCESS, inputs: \u001b[38;5;28mdict\u001b[39m[\u001b[38;5;28mstr\u001b[39m, Any] \u001b[38;5;241m|\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs: Any\n\u001b[1;32m    282\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m ResultAndNode:\n\u001b[1;32m    283\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Run the process with the supplied inputs in this runner that will block until the process is completed.\u001b[39;00m\n\u001b[1;32m    284\u001b[0m \n\u001b[1;32m    285\u001b[0m \u001b[38;5;124;03m    The return value will be the results of the completed process\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    289\u001b[0m \u001b[38;5;124;03m    :return: tuple of the outputs of the process and the calculation node\u001b[39;00m\n\u001b[1;32m    290\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 291\u001b[0m     result, node \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_run\u001b[49m\u001b[43m(\u001b[49m\u001b[43mprocess\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43minputs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    292\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m ResultAndNode(result, node)\n",
      "File \u001b[0;32m~/.aiida_venvs/lucia/lib/python3.10/site-packages/aiida/engine/runners.py:261\u001b[0m, in \u001b[0;36mRunner._run\u001b[0;34m(self, process, inputs, **kwargs)\u001b[0m\n\u001b[1;32m    259\u001b[0m     signal\u001b[38;5;241m.\u001b[39msignal(signal\u001b[38;5;241m.\u001b[39mSIGINT, kill_process)\n\u001b[1;32m    260\u001b[0m     signal\u001b[38;5;241m.\u001b[39msignal(signal\u001b[38;5;241m.\u001b[39mSIGTERM, kill_process)\n\u001b[0;32m--> 261\u001b[0m     \u001b[43mprocess_inited\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    262\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    263\u001b[0m     signal\u001b[38;5;241m.\u001b[39msignal(signal\u001b[38;5;241m.\u001b[39mSIGINT, original_handler_int)\n",
      "File \u001b[0;32m~/.aiida_venvs/lucia/lib/python3.10/site-packages/plumpy/processes.py:90\u001b[0m, in \u001b[0;36mensure_not_closed.<locals>.func_wrapper\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m     88\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_closed:\n\u001b[1;32m     89\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m exceptions\u001b[38;5;241m.\u001b[39mClosedError(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mProcess is closed\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m---> 90\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.aiida_venvs/lucia/lib/python3.10/site-packages/plumpy/processes.py:1203\u001b[0m, in \u001b[0;36mProcess.execute\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1200\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhas_terminated():\n\u001b[1;32m   1201\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mloop\u001b[38;5;241m.\u001b[39mrun_until_complete(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mstep_until_terminated())\n\u001b[0;32m-> 1203\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfuture\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[0;31mKilledError\u001b[0m: Process was killed because the runner received an interrupt"
     ]
    }
   ],
   "source": [
    "inputs['skip_uc'] = orm.Bool(False)\n",
    "inputs['n_layers'] =orm.Int(12)\n",
    "inputs['slipping_system'] = orm.List(['A2', '110'])\n",
    "\n",
    "logging.getLogger('aiida.transport.SshTransport') .setLevel(logging.ERROR)\n",
    "logging.getLogger('aiida.scheduler.slurm').setLevel(logging.ERROR)\n",
    "\n",
    "test_node = run.get_node(USFWorkChain, **inputs)\n",
    "test_USF_group.add_nodes(test_node.node)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# TEST B1 -- AsTe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "import yaml\n",
    "\n",
    "ase_atom = read('./structures/cif/mpds-S1605628-AsTe-225-B1.cif', format='cif')\n",
    "structure = orm.StructureData(ase=ase_atom)\n",
    "\n",
    "pseudo_family = orm.load_group('PseudoDojo/0.5/PBE/SR/standard/upf')\n",
    "\n",
    "pseudos = pseudo_family.get_pseudos(structure=structure)\n",
    "\n",
    "cutoff_wfc, cutoff_rho = pseudo_family.get_recommended_cutoffs(\n",
    "    structure=structure,\n",
    "    unit='Ry'\n",
    ")\n",
    "\n",
    "kpoints = orm.KpointsData()\n",
    "kpoints.set_kpoints_mesh([14, 14, 14])\n",
    "\n",
    "settings = orm.Dict({\n",
    "    # 'cmdline': ['-npool', '2']\n",
    "})\n",
    "\n",
    "usf_overrides_yaml = open('./usf-lucia.yaml')\n",
    "usf_overrides = yaml.safe_load(usf_overrides_yaml)\n",
    "\n",
    "inputs = {}\n",
    "\n",
    "\n",
    "inputs['metadata'] = usf_overrides.get('metadata', {})\n",
    "inputs['structure'] = structure\n",
    "inputs['kpoints'] = kpoints\n",
    "inputs['pw'] = usf_overrides.get('pw', {})\n",
    "inputs['pw']['pseudos'] = pseudos\n",
    "inputs['pw']['code'] = pw_code\n",
    "inputs['pw']['parameters']['CONTROL']['disk_io'] = 'nowf'\n",
    "inputs['pw']['parameters']['SYSTEM']['degauss'] = 0.02\n",
    "inputs['pw']['parameters']['ELECTRONS']['conv_thr'] = 1e-5\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## {100} surface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "04/28/2025 07:44:34 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137980|USFWorkChain|validate_slipping_system]: FCC element crystal <space group #225, prototype NaCl>. I don't know the usual gliding plane. \n",
      "04/28/2025 07:44:35 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137980|USFWorkChain|validate_slipping_system]: Now we are working on 100 gliding plane.\n",
      "04/28/2025 07:44:35 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137980|USFWorkChain|validate_slipping_system]: Faulting is possible for 100 gliding plane.The stacking order is AB. Slipping direction: 1/2[010]. \n",
      "04/28/2025 07:44:35 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137980|USFWorkChain|run_scf]: launching PwCalculation<1137981> for AsTe unit cell geometry.\n",
      "04/28/2025 07:45:49 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137980|USFWorkChain|inspect_scf]: SCF calculation<1137981> finished\n",
      "04/28/2025 07:45:49 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137980|USFWorkChain|run_USF]: Multiplicity of the faulted geometry: 8\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1314' coro=<interruptable_task.<locals>.execute_coroutine() done, defined at /home/yzhang/.aiida_venvs/lucia/lib/python3.10/site-packages/aiida/engine/utils.py:134> exception=KillInterruption('Killed by parent<1137961>')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/yzhang/.aiida_venvs/lucia/lib/python3.10/site-packages/aiida/engine/utils.py\", line 144, in execute_coroutine\n",
      "    future.result(),\n",
      "plumpy.process_states.KillInterruption: Killed by parent<1137961>\n",
      "04/28/2025 07:45:50 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137980|USFWorkChain|run_USF]: launching PwCalculation<1137989> for USF geometry.\n",
      "04/28/2025 07:53:20 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137980|USFWorkChain|inspect_USF]: SCF calculation<1137989> for USF geometry finished\n",
      "04/28/2025 07:53:20 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137980|USFWorkChain|results]: Energy difference per surface area: uuid: 01d5dda1-f17f-463b-92ab-bc9791fb94a9 (unstored) value: 0.2198839858206186 J/m^2\n",
      "04/28/2025 07:53:20 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137980|USFWorkChain|results]: Results\n",
      "04/28/2025 07:53:20 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1137980|USFWorkChain|on_terminated]: remote folders will not be cleaned\n"
     ]
    }
   ],
   "source": [
    "inputs['skip_uc'] = orm.Bool(False)\n",
    "inputs['n_layers'] =orm.Int(8)\n",
    "inputs['slipping_system'] = orm.List(['B1', '100'])\n",
    "\n",
    "logging.getLogger('aiida.transport.SshTransport') .setLevel(logging.ERROR)\n",
    "logging.getLogger('aiida.scheduler.slurm').setLevel(logging.ERROR)\n",
    "\n",
    "test_node = run.get_node(USFWorkChain, **inputs)\n",
    "test_USF_group.add_nodes(test_node.node)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## {110} surface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "04/28/2025 08:10:56 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138008|USFWorkChain|validate_slipping_system]: FCC element crystal <space group #225, prototype NaCl>. I don't know the usual gliding plane. \n",
      "04/28/2025 08:10:56 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138008|USFWorkChain|validate_slipping_system]: Now we are working on 110 gliding plane.\n",
      "04/28/2025 08:10:56 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138008|USFWorkChain|validate_slipping_system]: Faulting is possible for 110 gliding plane.The stacking order is AB. Slipping direction: 1/2[112]. \n",
      "04/28/2025 08:10:57 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138008|USFWorkChain|run_scf]: launching PwCalculation<1138009> for AsTe unit cell geometry.\n",
      "04/28/2025 08:12:11 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138008|USFWorkChain|inspect_scf]: SCF calculation<1138009> finished\n",
      "04/28/2025 08:12:11 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138008|USFWorkChain|run_USF]: Multiplicity of the faulted geometry: 8\n",
      "04/28/2025 08:12:12 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138008|USFWorkChain|run_USF]: launching PwCalculation<1138017> for USF geometry.\n",
      "04/28/2025 08:19:19 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138008|USFWorkChain|inspect_USF]: SCF calculation<1138017> for USF geometry finished\n",
      "04/28/2025 08:19:19 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138008|USFWorkChain|results]: Energy difference per surface area: uuid: 17b6d6a1-4061-4938-b02f-42665dbfaf84 (unstored) value: 9.668085232456233 J/m^2\n",
      "04/28/2025 08:19:19 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138008|USFWorkChain|results]: Results\n",
      "04/28/2025 08:19:19 PM <139415> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138008|USFWorkChain|on_terminated]: remote folders will not be cleaned\n"
     ]
    }
   ],
   "source": [
    "inputs['skip_uc'] = orm.Bool(False)\n",
    "inputs['n_layers'] =orm.Int(8)\n",
    "inputs['slipping_system'] = orm.List(['B1', '110'])\n",
    "\n",
    "logging.getLogger('aiida.transport.SshTransport') .setLevel(logging.ERROR)\n",
    "logging.getLogger('aiida.scheduler.slurm').setLevel(logging.ERROR)\n",
    "\n",
    "test_node = run.get_node(USFWorkChain, **inputs)\n",
    "test_USF_group.add_nodes(test_node.node)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## {111} surface"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# TEST HALF-HEUSLER"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import yaml\n",
    "\n",
    "ase_atom = read('./structures/cif/mpds-S1612207-NbCoSb-216-C1b.cif', format='cif')\n",
    "structure = orm.StructureData(ase=ase_atom)\n",
    "\n",
    "pseudo_family = orm.load_group('PseudoDojo/0.5/PBE/SR/standard/upf')\n",
    "\n",
    "pseudos = pseudo_family.get_pseudos(structure=structure)\n",
    "\n",
    "cutoff_wfc, cutoff_rho = pseudo_family.get_recommended_cutoffs(\n",
    "    structure=structure,\n",
    "    unit='Ry'\n",
    ")\n",
    "\n",
    "kpoints = orm.KpointsData()\n",
    "kpoints.set_kpoints_mesh([12, 12, 12])\n",
    "\n",
    "settings = orm.Dict({\n",
    "    # 'cmdline': ['-npool', '2']\n",
    "})\n",
    "\n",
    "usf_overrides_yaml = open('./usf-lucia.yaml')\n",
    "usf_overrides = yaml.safe_load(usf_overrides_yaml)\n",
    "\n",
    "inputs = {}\n",
    "\n",
    "inputs['metadata'] = usf_overrides.get('metadata', {})\n",
    "inputs['structure'] = structure\n",
    "inputs['kpoints'] = kpoints\n",
    "inputs['pw'] = usf_overrides.get('pw', {})\n",
    "inputs['pw']['pseudos'] = pseudos\n",
    "inputs['pw']['code'] = pw_code\n",
    "inputs['pw']['parameters']['CONTROL']['disk_io'] = 'nowf'\n",
    "inputs['pw']['parameters']['SYSTEM']['degauss'] = 0.02\n",
    "inputs['pw']['parameters']['ELECTRONS']['conv_thr'] = 1e-5\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## {100} surface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "04/29/2025 11:00:02 AM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138093|USFWorkChain|validate_slipping_system]: We are doing half-heusler-type structure. <space group #216, prototype MgSiAl>. I don't know the usual gliding plane. \n",
      "04/29/2025 11:00:02 AM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138093|USFWorkChain|validate_slipping_system]: Now we are working on 100 gliding plane.\n",
      "04/29/2025 11:00:02 AM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138093|USFWorkChain|validate_slipping_system]: Faulting is possible for 100 gliding plane.The stacking order is ABCD. Slipping direction: 1/2[100]. \n",
      "04/29/2025 11:00:02 AM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138093|USFWorkChain|run_scf]: launching PwCalculation<1138094> for CoNbSb unit cell geometry.\n",
      "04/29/2025 11:02:52 AM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138093|USFWorkChain|inspect_scf]: SCF calculation<1138094> finished\n",
      "04/29/2025 11:02:52 AM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138093|USFWorkChain|run_USF]: Multiplicity of the faulted geometry: 4.0\n",
      "04/29/2025 11:02:53 AM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138093|USFWorkChain|run_USF]: launching PwCalculation<1138102> for USF geometry.\n",
      "04/29/2025 11:11:02 AM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138093|USFWorkChain|inspect_USF]: SCF calculation<1138102> for USF geometry finished\n",
      "04/29/2025 11:11:03 AM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138093|USFWorkChain|results]: Energy difference per surface area: uuid: c399bb9f-c0d9-4ad1-8c10-0b932c3e8fbe (unstored) value: 2.776532385083423 J/m^2\n",
      "04/29/2025 11:11:03 AM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138093|USFWorkChain|results]: Results\n",
      "04/29/2025 11:11:03 AM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138093|USFWorkChain|on_terminated]: remote folders will not be cleaned\n"
     ]
    }
   ],
   "source": [
    "inputs['skip_uc'] = orm.Bool(False)\n",
    "inputs['n_layers'] =orm.Int(8)\n",
    "inputs['slipping_system'] = orm.List(['C1b', '100'])\n",
    "\n",
    "logging.getLogger('aiida.transport.SshTransport').setLevel(logging.ERROR)\n",
    "logging.getLogger('aiida.scheduler.slurm').setLevel(logging.ERROR)\n",
    "\n",
    "test_node = run.get_node(USFWorkChain, **inputs)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# {110} surface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "04/29/2025 01:05:11 PM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138145|USFWorkChain|validate_slipping_system]: We are doing half-heusler-type structure. <space group #216, prototype MgSiAl>. I don't know the usual gliding plane. \n",
      "04/29/2025 01:05:11 PM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138145|USFWorkChain|validate_slipping_system]: Now we are working on 110 gliding plane.\n",
      "04/29/2025 01:05:11 PM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138145|USFWorkChain|validate_slipping_system]: Faulting is possible for 110 gliding plane.The stacking order is AB. Slipping direction: 1/2[110]. \n",
      "04/29/2025 01:05:12 PM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138145|USFWorkChain|run_scf]: launching PwCalculation<1138146> for CoNbSb unit cell geometry.\n",
      "04/29/2025 01:06:27 PM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138145|USFWorkChain|inspect_scf]: SCF calculation<1138146> finished\n",
      "04/29/2025 01:06:28 PM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138145|USFWorkChain|run_USF]: Multiplicity of the faulted geometry: 4.0\n",
      "04/29/2025 01:06:28 PM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138145|USFWorkChain|run_USF]: launching PwCalculation<1138154> for USF geometry.\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1134' coro=<interruptable_task.<locals>.execute_coroutine() done, defined at /home/yzhang/.aiida_venvs/lucia/lib/python3.10/site-packages/aiida/engine/utils.py:134> exception=KillInterruption('Killed by parent<1138127>')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/yzhang/.aiida_venvs/lucia/lib/python3.10/site-packages/aiida/engine/utils.py\", line 144, in execute_coroutine\n",
      "    future.result(),\n",
      "plumpy.process_states.KillInterruption: Killed by parent<1138127>\n",
      "04/29/2025 01:30:30 PM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138145|USFWorkChain|inspect_USF]: SCF calculation<1138154> for USF geometry finished\n",
      "04/29/2025 01:30:30 PM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138145|USFWorkChain|results]: Energy difference per surface area: uuid: 00fe1353-a077-4251-8aeb-a60322d3e8b4 (unstored) value: 16.547806628950784 J/m^2\n",
      "04/29/2025 01:30:30 PM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138145|USFWorkChain|results]: Results\n",
      "04/29/2025 01:30:31 PM <293207> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [1138145|USFWorkChain|on_terminated]: remote folders will not be cleaned\n"
     ]
    }
   ],
   "source": [
    "inputs['skip_uc'] = orm.Bool(False)\n",
    "inputs['n_layers'] =orm.Int(8)\n",
    "inputs['slipping_system'] = orm.List(['C1b', '110'])\n",
    "inputs['pw']['parameters']['ELECTRONS']['mixing_beta'] = 0.4\n",
    "\n",
    "logging.getLogger('aiida.transport.SshTransport').setLevel(logging.ERROR)\n",
    "logging.getLogger('aiida.scheduler.slurm').setLevel(logging.ERROR)\n",
    "\n",
    "test_node = run.get_node(USFWorkChain, **inputs)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "lucia",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
